---
# https://wiki.x2go.org/doku.php/doc:installation:x2goserver
- name: Add repo 4 Debian, but not for Ubuntu
  when:
    - ansible_os_family == 'Debian'
    - ansible_distribution != 'Ubuntu'
    - ansible_pkg_mgr == 'apt'
  become: yes
  block:
    - apt_key:
        url: https://packages.x2go.org/pub.key
        state: present
    - apt_key:
        keyserver: keys.gnupg.net
        id: E1F958385BFE2B6E
        state: present
    - apt_repository:
        repo: deb {{ http_or_https }}://packages.x2go.org/debian {{ ansible_distribution_release }} extras {{ x2go_repo_version_fact }}
        filename: x2go
        mode: 644
        state: present

# https://launchpad.net/~x2go/+archive/ubuntu/stable
# https://launchpad.net/~x2go/+archive/ubuntu/ppa
# https://launchpad.net/~x2go/+archive/ubuntu/saimaa
- name: Add repo x2go 4 Ubuntu
  when:
    - ansible_os_family == 'Debian'
    - ansible_distribution == 'Ubuntu'
    - ansible_pkg_mgr == 'apt'
  become: yes
  block:
    - apt_repository:
        repo: ppa:x2go/stable
        mode: 644
        state: present
      when: x2go_repo_version == 'release'
    - apt_repository:
        repo: ppa:x2go/ppa
        mode: 644
        state: present
      when: x2go_repo_version == 'nightly'
    - apt_repository:
        repo: ppa:x2go/saimaa
        mode: 644
        state: present
      when: x2go_repo_version == 'esr'

- name: Add EPEL repo 4 CentOS 7\RHEL
  when:
    - ansible_os_family == 'RedHat'
    - ansible_pkg_mgr == 'yum'
  vars:
    # https://stackoverflow.com/a/47091066/5430535
    # https://github.com/ansible/ansible/issues/32532#issuecomment-341641007
    ansible_python_interpreter: /usr/bin/python2.7
  become: yes
  # https://fedoraproject.org/wiki/EPEL
  package:
    name:
      - epel-release
    state: present

- name: Add EPEL repo 4 CentOS 8+\RHEL
  when:
    - ansible_os_family == 'RedHat'
    - ansible_pkg_mgr == 'dnf'
    - ansible_distribution != 'Fedora'
  become: yes
  package:
    name:
      - epel-release
    state: present

# [x2go-release-epel]
# name=Upstream X2Go EPEL Packages (Release Builds)
# baseurl=http://packages.x2go.org/epel/$releasever/main/$basearch
# gpgcheck=1
# gpgkey=http://packages.x2go.org/pub.key
# enabled=1
# protect=0
- name: Add repo x2go 4 CentOS\RHEL
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version != '8'
  become: yes
  yum_repository:
    file: x2go
    name: x2go-{{ x2go_repo_version }}-epel
    description: Upstream X2Go EPEL Packages ({{ x2go_repo_version_fact }} Builds)
    baseurl: '{{ http_or_https }}://packages.x2go.org/epel/$releasever/{{ x2go_repo_version_fact }}/$basearch'
    gpgkey: https://packages.x2go.org/pub.key
    enabled: yes
    gpgcheck: yes
    state: present

# https://wiki.x2go.org/doku.php/wiki:repositories:suse
- name: Add repo x2go 4 {{ ansible_distribution }}
  when:
    - ansible_system == 'Linux'
    - ansible_os_family == 'Suse'
    - ansible_pkg_mgr == 'zypper'
    - ansible_distribution == 'openSUSE Leap'
  become: yes
  zypper_repository:
    name: 'x2go Repository'
    repo: '{{ http_or_https }}://download.opensuse.org/repositories/X11:/RemoteDesktop:/x2go/{{ ansible_distribution | replace(" ", "_") }}_{{ ansible_distribution_version }}/'
    state: present
    auto_import_keys: yes
    runrefresh: yes

- name: Add repo x2go 4 {{ ansible_distribution }}
  when:
    - ansible_system == 'Linux'
    - ansible_os_family == 'Suse'
    - ansible_pkg_mgr == 'zypper'
    - ansible_distribution == 'openSUSE Tumbleweed'
  become: yes
  zypper_repository:
    name: 'x2go Repository'
    repo: '{{ http_or_https }}://download.opensuse.org/repositories/X11:/RemoteDesktop:/x2go/{{ ansible_distribution | replace(" ", "_") }}/'
    state: present
    auto_import_keys: yes
    runrefresh: yes
